### ISSUE TITLE
Streck i headern på Firefox och Edge

### ISSUE THREAD

**Issue by Loosergirl** [DanteUh/asap-development#26]

**Comment by jesperengstrom** [comment]
Kanske löst sedan vi pushade upp margin -1 på polygonen?

**Comment by Loosergirl** [comment]
Jag vet att det plötsligt började funka i IE11. Ladda ned Firefox och kolla själv.

**Comment by jesperengstrom** [comment]
Har fixat så att det ser bra ut i Firefox! Kan nån kolla så att det funkar i Edge (har ej win10) så kan vi stänga denna!

**Comment by DanteUh** [comment]
Den fungerar perfa på Edge :)
